# Config DB
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update

# OpenApi
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.defaultModelsExpandDepth=2
springdoc.override-with-generic-response=false
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true